# test against this verision of Node.js
environment:
	matrix:
		#Node.js
		- nodejs_version: "6"

# Install scripts (runs after repo cleaning)
install:
	# Get the latest version of Node.js
	- ps: Install-Product node $env:nodejs_version
	# Install modules
	- npm install

# Post-install test scripts
test_script:
	# Output useful info for debugging
	- node --version
	- npm --version
	# Run tests
	- npm test

# Don't actually build
build: off
